volumes:
  etc_wireguard:

services:
  amnezia-wg-go-easy:
    env_file:
      - .env
    image: ghcr.io/reduxvzr/amnezia-wg-easy
    container_name: amnezia-wg-go-easy
    volumes:
      - etc_wireguard:/etc/amnezia/amneziawg
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    devices:
    - /dev/net/tun:/dev/net/tun
